### PR TITLE
Add support for linting Jupyter notebooks through nbQA

### PR DESCRIPTION
**Pull request by damiondoesthings**
Hey,

I had issues running mypy baseline for Jupyter notebooks through [nbQA](https://github.com/nbQA-dev/nbQA). Mainly the output from mypy is slightly different (e.g. includes the cell number) and seems to be double escaped when piping from nbQA into mypy-baseline.

I added a function to strip the color characters from the input string, I believe this solution is a bit simpler, as the regex for getting the double escaped color codes would have gotten very complex.

Also added some basic tests. For me all commands seem to work fine. Let me know, if you would like anything changed

### CODE REVIEW

**Comment by orsinium** [comment]
Thank you, that's quite interesting. Could you fix linter violations, please? You can run formatters, linters, and tests locally by installing [task](https://taskfile.dev/installation/) and then running `task all`.

I had a quick look at the changes. Seems fine, but I'll take a bit more time later to add a bit more tests. I'm worried a bit about the changes in how color codes are handled.

**Comment by damiondoesthings** [comment]
Thanks for the feedback. I fixed the lints, there are still 2 mypy errors, but in unrelated lines.
```
mypy_baseline/_config.py:21: error: Unused "type: ignore" comment
mypy_baseline/_config.py:23: error: Unused "type: ignore" comment
```
 
 Regarding the color code handling, I think getting the right Regex and handling them the same as before, might be a cleaner solution, I unfortunately could not figure it out.
 
Just wondering if this double escaping or double encoding of the color codes is maybe a shell specific issue? For reference I am using zsh.

**Comment by orsinium** [comment]
That's alright, it's a good change I think, we shouldn't try to put everything into one big scary regex. I just want to be 100% sure the behavior didn't change :)

**Comment by orsinium** [comment]
I went through the code, tested it with mypy and nbqa, and everything works perfectly. I moved around the docs a bit, I want the readme to be minimalistic, but that's it. Great work! Thank you for your contribution :)

**Comment by orsinium** [comment]
The changes are released as 0.5.0 ✅

**Pull request merged**
